name: "♻️ Python test"

on:
  workflow_call:

jobs:
  python_test:
    name: Run pytest
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup python
        uses: ./.github/actions/setup_python

      - name: Install dependencies
        run: poetry install --only main,ci-test

      - name: Run test
        run: poetry run pytest ./test/
